[package]
name = "receptionist"
version = "0.1.0"
edition = "2021"

[lib]
# disabled since this project do NOT have documentation
doctest = false

[dependencies]
anyhow = { workspace = true }
common = { path = "../libcommon" }
chrono = "0.4"
dotenv = "0.15"
