[package]
name = "pacient"
version = "0.1.0"
edition = "2021"

[lib]
# disabled since this project do NOT have documentation
doctest = false

[dependencies]
common = { path = "../libcommon" }
dotenv = "0.15"
serde = { workspace = true }
serde_derive = { workspace = true }
